import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import '@splidejs/react-splide/css';
  import "aos/dist/aos.css";


const RobotoCondensed = Roboto_Condensed({
  weight: ['300','400','500','600','700'],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tutopia Pro",
  description: "Generated by create react app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${RobotoCondensed.className} antialiased`}
      >
        <AppRouterCacheProvider>
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
